### PR TITLE
Implemented rudimentary Enemies

### LINKED ISSUE #41: Implement Enemies
Make Enemeies Move independently.

Implement Logic for how they move; towards the player etc.

### LINKED ISSUE #86: Unify HP system: Only `Actor`s should have HP, and the existing fields `hp` and `maxHp` should be used

### PR DESCRIPTION
**Pull request by l-augull**
Implemented basic Enemy type

Current issues:
- No logic, Mobs always walk and shoot directly towards player regardless of walls
- Turning happens instantly
- Mobs currently only target Player 1

I will get to work on improving these issues, but created a pr to have something to show regardless

### CODE REVIEW

**Comment by Ludwig-Work** [comment]
Enemies now target whichever player is closest to them.
The doubly-drawing of enemies has been fixed.
The other two issues are still valid.

**Review by Ludwig-Work — DISMISSED** [review]
I built on what you started and tried to enhance the enemies.
Turning no longer happens instantly, and they also have some "logic" (based on randomness) to help them when they are stuck in a corner. Not intelligent yet, but at least not stupidly running in one direction.

For me, we can merge it like this, but I'll let you review my changes too  :​)

**Comment by Ludwig-Work** [comment]
(@l-augull I can't request your review on this, since you author the pull request, but feel free to give your comment on my changes).

**Review by Ludwig-Work — APPROVED** [review]

**Review by Phil-Ebsworth — APPROVED** [review]
tested and works fine

**Pull request merged**
