### PR TITLE
Level selection screen to dynamically load levels from tmx files

### LINKED ISSUE #34: Select one of the existing arenas from the main menu

### PR DESCRIPTION
**Pull request by Ludwig-Work**

### CODE REVIEW

**Review by l-augull — DISMISSED** [review]
Looks good.

Only minor improvement would be to display the Level Number Select Buttons in a sorted order; if there are more than 2 it looks weird.

**Comment by Ludwig-Work** [comment]
Oops, they are not sorted? I thought they were.
I'll fix this in the beginning of the next sprint then.

**Comment by Ludwig-Work** [comment]
They are now ordered lexicographically (like the files are ordered in the file system too). 
If we have multiple-digit level numbers, we may need to introduce leading zeros in the file names to fix that order.
But other than that, the buttons should now be ordered correctly.

**Review by l-augull — APPROVED** [review]
Looks good :)

**Pull request merged**
