### PR TITLE
Updating movement of robot.

### LINKED ISSUE #22: Enhance robot class
BasicRobot needs the following fields:

- Current acceleration `a`
- Maximum acceleration `a_max`
- Velocity in direction `v`
- Current rotational acceleration `a_alpha`
- Maximum rotational acceleration: `a_alpha_max`
- Rotational velocity `v_alpha`

### PR DESCRIPTION
**Pull request by KevinDwo**
Changes:

- (Moves like a car.) You can accelerate and it starts moving, till you step on the breaks
- The direction no longer follows the mouse, but can be changed clicking on the left/right key

Most calculations are done in game class

### CODE REVIEW

**Review by Phil-Ebsworth — COMMENTED** [review]
why do you change the rotation from mouse to buttons?

- movement might be to slow
- rotation is holding on after button release
- movement is counterintuitive

**Comment by KevinDwo** [comment]
Thats what we should do according to the sprint. Or did I misunderstand some parts? 

I can make it faster though.

**Comment by Ludwig-Work** [comment]
I think changing rotations with buttons is fine since the sprint wanted us to do that and we were also talking about controller support earlier? In that case, a mouse isn't available anyway. I'll go ahead and resolve the merge conflicts and then review this.

**Review by Ludwig-Work — CHANGES_REQUESTED** [review]
We need to think about this a little more I believe. Perhaps both rotation and velocity should automatically decelerate if no button is pressed? The current endless motion doesn't feel natural to me at least. 

What's an issue is that the velocities are fields of `Game` and not of `BasicRobot`. Currently, when you accelerate, then switch to another robot (Number key `1` - `4`), the motion is transferred to that other robot.

Another issue is with the current `direction` calculation, the new robot sprites appear to move sideways.

Probably this is the first thing to address in the next sprint.

**Review by Ludwig-Work — DISMISSED** [review]
Update: We decided to merge this and sort out the issues with future pull requests, so let's go ahead! :​)

**Review by l-augull — APPROVED** [review]
Solved merge conflict

**Pull request merged**
