### PR TITLE
Added level3

### LINKED ISSUE #101: Adding Level 3

### PR DESCRIPTION
**Pull request by KevinDwo**
Added another level. Tried to make it a bit more open.

Closes #101

### CODE REVIEW

**Review by Ludwig-Work — CHANGES_REQUESTED** [review]
Level looks nice and is definitely an increase in difficulty compared to levels 1 and 2! :​)

Some tiles appear to be in the wrong layers though. I tried to find all of them, here's what I found:
(Edit: I checkmarked the ones that are fixed.)

- [x] The second vertical wall at the top of the screen is in `WallsLowerHalf` instead of `WallsRightQuarter`.
- [x] The vertical wall to the right of the player's starting positions is in `WallsLowerHalf` instead of `WallsLeftQuarter`
- [x] There is an invisible, non-empty tile in `WallsLowerHalf` to the right of the player's starting positions.
- [x] The puddle in the upper right corner is not only in `Decoration` but also in `Obstacles`, not allowing the player to pass through.
- [ ] The closed gate in the upper horizontal wall of the bottom right corner is not only in `Decoration` but also in `Obstacles`, not allowing the player to pass behind it.
- [x] The Top→Right corner tile right in the middle of the screen should be in `WallsRightQuarter` instead of `WallsLowerHalf` to allow the player to pass at its side
- [ ] One `Ground` tile is different from the others (this one doesn't really matter since it cannot be seen, though).

Would you like to fix those? 
If you'd like, I could do it for you, too.

**Comment by KevinDwo** [comment]
I think now all tiles are on the right level.

**Comment by Ludwig-Work** [comment]
There are two more from my list. Imma go ahead and fix them real quick.

**Review by Ludwig-Work — APPROVED** [review]
Now everything's great

**Pull request merged**
