### PR TITLE
Fix collision detection by colliding pygame.Rect objects

### LINKED ISSUE #77: Fix Collision Detection

### LINKED ISSUE #85: Perspective: Make robots able to move "behind" horizontal walls

### PR DESCRIPTION
**Pull request by Ludwig-Work**
The collision now really works with the entity hitboxes, and the (deadly and normal) obstacles are stored as `Rect`s for a precise collision detection.

Problem: Not all walls are actually as wide or as long as a tile. Possible ways of fixing that that come to my mind:
- For each obstacle, store only the smallest possible rect that holds all of its non-transparent pixels **OR**
- Introduce different kinds of obstacles (for "obstacle only in upper third of the tile", "obstacle only in left third of the tile", "obstacle in the whole tile")

I'm still trying to figure out a working solution.

**Edit:** I went with my second suggestion and split the `Walls` layer into three separate layers depending on where the `Rect` obstacle should be.

### CODE REVIEW

**Comment by Ludwig-Work** [comment]
Problem: Perspective needs to be fixed. Draw `WallsLowerHalf` tiles *above* entities, not below, so the 2.5D perspective looks correct.

**Comment by Ludwig-Work** [comment]
This looks pretty good now IMO, the only flaw is that the HP bars are not drawn above the walls.

**Comment by Ludwig-Work** [comment]
I'm happy with this now.
Feel free to review :​)

**Review by KevinDwo — APPROVED** [review]
I played it a bit and works fine. 
Going through the small doors feels a bit weird though.

Small adjustments:
- Removed a parantheses around an if-clause
- Simplified another if-clause

**Comment by Ludwig-Work** [comment]
> Going through the small doors feels a bit weird though.

Yes, that's because they are one tile high, which is *exactly* the height of the player. 
The rectangle can therefore only move through them in a straight horizontal line.

Fixing that would probably mean making the players a bit smaller, or the collision detection a lot more complex.
Since that would be out of scope for this pull request (could be addressed later), and the way it currently works is *working*, I think this can be merged.

**Comment by Ludwig-Work** [comment]
Thanks for your adjustments :​)

**Pull request merged**
