### PR TITLE
improved Interface

### LINKED ISSUE #55: Background Music

### LINKED ISSUE #70: Beautify menu interface

### PR DESCRIPTION
**Pull request by Phil-Ebsworth**
Added:

- textures for buttons and background
- hover effect for buttons
- added music

Resolves #55 
Resolves #70

### CODE REVIEW

**Review by KevinDwo — DISMISSED** [review]
Looks very good.

Just one thing do you ever use the "panel" class? It seems like you always use "titel" class. 
If so I would consider deleting it for clarity/simplicity.

Or do we need it for later changes?

**Review by Ludwig-Work — CHANGES_REQUESTED** [review]
Menu design looks great! I found two issues:
- The music starts playing when going to level select screen and back to main menu, but it doesn't play initially in the main menu
- From the game, pressing the escape key crashes the program.

**Comment by Ludwig-Work** [comment]
And tbh this doesn't resolve #48 (Issue description: `HP Bar, Wave counter, Time? Score?`). The menu interface should probably be a seperate issue.

**Comment by Phil-Ebsworth** [comment]
> Menu design looks great! I found two issues:
> 
> * The music starts playing when going to level select screen and back to main menu, but it doesn't play initially in the main menu
> * From the game, pressing the escape key crashes the program.

solved the music issue, couldn't recreate crash

**Comment by Ludwig-Work** [comment]
The crash is this:
```
File "Roboarena\Menus\mainmenu.py", line 34, in process
    if event.type == pygame.MOUSEBUTTONUP:
       ^^^^^
UnboundLocalError: cannot access local variable 'event' where it is not associated with a value
```
In `mainmenu.py`, if `pygame.event.get()` returns an empty list in line 25, the variable `event` is never bound to a value, but it is used in line 34.

Another (smaller) issue is that my console is full of
```
libpng warning: iCCP: known incorrect sRGB profile
```
warnings after the program ran.

**Review by Ludwig-Work — APPROVED** [review]
Great, looks perfect to me now.

**Pull request merged**
